[oci]
; extension = extensions/oci8.so
; 下载并安装 Oracle Instant Client
[pdo_oci]
; extension = extensions/pdo_oci.so
; 下载并安装 Oracle Instant Client
[swoole]
extension = extensions/swoole.so
    
[redis]
extension = extensions/redis.so

[mongodb]                                      
extension = extensions/mongodb.so